@echo off
cd conv
dcc32 xxmConv.dpr
dcc32 xxmProject.dpr
cd ..\proto
dcc32 xxmProto.dpr
cd ..\http
dcc32 xxmHttpAU.dpr
dcc32 xxmHttpDev.dpr
dcc32 xxmHttpSvc.dpr
dcc32 xxmHttpSvcAU.dpr
dcc32 xxmHttp.dpr
cd ..\isapi
dcc32 xxmIsapiAU.dpr
dcc32 xxmIsapiDev.dpr
dcc32 xxmIsapiEx.dpr
cd ..\cgi
dcc32 xxmCGI.dpr
dcc32 xxmHost.dpr
dcc32 xxmHostAU.dpr
dcc32 xxmHostDev.dpr
dcc32 xxmHostSvc.dpr
dcc32 xxmHostSvcAU.dpr
cd ..\apache
dcc32 xxmAhttpd.dpr
dcc32 xxmAhttpdAU.dpr
dcc32 xxmAhttpdDev.dpr
cd ..\hsys
dcc32 xxmHSys1.dpr
dcc32 xxmHSys1AU.dpr
dcc32 xxmHSys1Dev.dpr
dcc32 xxmHSys1Svc.dpr
dcc32 xxmHSys1SvcAU.dpr
dcc32 xxmHSys2.dpr
dcc32 xxmHSys2AU.dpr
dcc32 xxmHSys2Dev.dpr
dcc32 xxmHSys2Svc.dpr
dcc32 xxmHSys2SvcAU.dpr
cd ..\..
pause